FEAT: Crafty crate added!
Yarden-zamir/Create-Prepare-to-Dye pull request #454
Opened 2023-12-28 10:29 UTC by chipsams

also of note: open crate now accessible in furnished device, alternate pre-wool recipe for furnished device.

2023-12-28 10:40 UTC, Yarden-zamir reviewed
Looks good, should move the pattern removal into it's own feature and perhapse think abit about the relation between slot cover and placeholder

2023-12-28 10:40 UTC, Yarden-zamir commented on kubejs/server_scripts/base/featrues/devices.js
> +          e.recipes.create.deploying("botania:placeholder",["#forge:concrete",Ingredient.of(["botania:crafty_crate","create:mechanical_crafter"])]).keepHeldItem();
Maybe a slot cover makes more sense? As it does the same thing for create autocrafting. Hm.. I wish we could just combine them

2023-12-28 10:40 UTC, Yarden-zamir commented on kubejs/server_scripts/base/featrues/devices.js
> +        //patterns kinda make some things too easy, e.g. unpacking storage blocks. we decided that packing is fine though, although we could probably change our minds later.
I think remove patterns is not related to devices, should be it's own feature in a seperate file

2023-12-28 10:40 UTC, Yarden-zamir commented on kubejs/server_scripts/base/featrues/devices.js
> +        //patterns kinda make some things too easy, e.g. unpacking storage blocks. we decided that packing is fine though, although we could probably change our minds later.
Also, you can removeItems instead of your own loop

2023-12-28 10:40 UTC, Yarden-zamir requested changes
Looks good, should move the pattern removal into it's own feature and perhapse think abit about the relation between slot cover and placeholder

2023-12-29 08:40 UTC, chipsams commented
> Looks good, should move the pattern removal into it's own feature and perhapse think abit about the relation between slot cover and placeholder

@Yarden-zamir ok, made them interchangable like we discussed on discord, although we are still yet to finalize on where they come from such that they are available with next to no progression.

2023-12-29 10:36 UTC, Yarden-zamir requested changes
Awesome. Can you move those features into their own file though?

2023-12-29 10:36 UTC, Yarden-zamir commented on kubejs/server_scripts/base/featrues/devices.js
> +        if(feature("Cheap Covers & Placeholders")){
Can you move this feature outside though? This is not related to devices.

2023-12-29 10:36 UTC, Yarden-zamir commented on kubejs/server_scripts/base/featrues/devices.js
> +        if(feature("Remove Crafty Crate Patterns")){
Same here. Should be in it's own independent feature not nested under devices

2023-12-29 15:58 UTC, Yarden-zamir approved these changes

2023-12-29 15:59 UTC, merged